"""Constants for unified API responses and request observability."""

REQUEST_ID_HEADER = "X-Request-ID"
REQUEST_ID_META_KEY = "request_id"

DEFAULT_SUCCESS_MESSAGE = "Operation completed successfully"
DEFAULT_ERROR_MESSAGE = "An unexpected error occurred"

ERROR_CODE_VALIDATION = "VALIDATION_ERROR"
ERROR_CODE_AUTHENTICATION_FAILED = "AUTHENTICATION_FAILED"
ERROR_CODE_NOT_AUTHENTICATED = "NOT_AUTHENTICATED"
ERROR_CODE_PERMISSION_DENIED = "PERMISSION_DENIED"
ERROR_CODE_NOT_FOUND = "NOT_FOUND"
ERROR_CODE_PARSE_ERROR = "PARSE_ERROR"
ERROR_CODE_METHOD_NOT_ALLOWED = "METHOD_NOT_ALLOWED"
ERROR_CODE_THROTTLED = "THROTTLED"
ERROR_CODE_SERVER_ERROR = "SERVER_ERROR"
