# Generated by Django 6.0.5 on 2026-05-17 16:11

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('address', models.TextField(blank=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_messes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('name', 'id'),
            },
        ),
        migrations.CreateModel(
            name='MessSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timezone', models.CharField(default='UTC', max_length=64)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('default_cutoff_time', models.TimeField(default=datetime.time(9, 0))),
                ('allow_late_changes', models.BooleanField(default=False)),
                ('grace_period_minutes', models.PositiveIntegerField(default=0)),
                ('attendance_default_behavior', models.CharField(choices=[('COUNT_PRESENT_IF_NO_ACTION', 'Count present if no action'), ('COUNT_ABSENT_IF_NO_ACTION', 'Count absent if no action')], default='COUNT_ABSENT_IF_NO_ACTION', max_length=32)),
                ('billing_mode', models.CharField(choices=[('FIXED_MONTHLY', 'Fixed monthly'), ('PER_MEAL', 'Per meal')], default='FIXED_MONTHLY', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mess', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='messes.mess')),
            ],
            options={
                'verbose_name_plural': 'Mess settings',
            },
        ),
        migrations.AddIndex(
            model_name='mess',
            index=models.Index(fields=['name'], name='messes_mess_name_a90548_idx'),
        ),
        migrations.AddIndex(
            model_name='mess',
            index=models.Index(fields=['is_active'], name='messes_mess_is_acti_35e9ff_idx'),
        ),
        migrations.AddIndex(
            model_name='mess',
            index=models.Index(fields=['owner', 'is_active'], name='messes_mess_owner_i_d293f4_idx'),
        ),
    ]
